@startuml
start

:Регистрация / Авторизация клиента;
if (Клиент зарегистрирован?) then (Да)
  :Система подтверждает учетные данные;
else (Нет)
  :Клиент регистрируется;
  :Система подтверждает учетные данные;
endif

:Оформление заказа;
:Клиент выбирает товары и добавляет в корзину;
:Клиент переходит к оформлению заказа (выбор доставки и оплаты);

:Проверка наличия товаров на складе;
if (Товар есть на складе?) then (Да)
  :Продолжение обработки заказа;
else (Нет)
  :Уведомление клиента об отсутствии;
  :Возможность выбрать замену или удалить товар;
endif

 :Оплата заказа;
fork
partition #lightGreen Клиент {

  :Клиент выбирает способ оплаты;
 
}
fork again
partition #lightGreen Система {
   :Система проверяет данные и проводит транзакцию;
  :Система уведомляет склад;
}
fork again
partition #lightGreen Сотрудник {
  :Сотрудник собирает заказ;
  :Подготовка заказа к отправке;
}
end fork

if (Оплата успешна И товар готов к отправке?) then (Да)
  :Генерация счета-фактуры;
  :Уведомление клиента о подтверждении заказа и статусе;
  :Статус заказа = "Отправлен";
else (Нет)
  if (Оплата не прошла) then (Да)
    :Уведомление клиента о проблеме с оплатой;
    :Клиент выбирает: повторить или сменить способ оплаты;
    if (Клиента не устраивает решение) then (Да)
      :Заказ отменяется;
      stop
    endif
  endif
endif

:Отслеживание и доставка заказа;
:Система обновляет статус;
:Клиент получает уведомления;

stop
@enduml